### ISSUE TITLE
Finish up P2P MVP

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#819]
When P2P mode is enabled:
- [x] Contribution button on NavBar should be accessible w/o login
- [x] Respond buttons on /contributions should only be visible to admins (#824)
- [x] Fix bug with `ClaimContribution` interactor missing params (#832)
- [x] Check if claiming sends an email
- [x] Remove person name in map view #847 
- [x] Re-enable registration #840 
- [x] ~Make email required on ask/offer forms (until sms is ready)~
- [x] Prevent claiming email-less contribution. #831
- [x] Redesign From section of Claim form, drop ability to override email, add disclaimer text no how to change your account email if you don't want others to see it. #855 
- [x]  View button on List view and Map view

Nice to have: 
- [ ] Implement `description` from #310.
- [ ] Add note in ContactMethods re looking up fontawesome icons

And then:
- [x] Cut a release!

**Comment by exbinary** [comment]
Done! w00t!
