### ISSUE TITLE
Tie up loose ends

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#991]
Documenting a list of loose ends and work-in-progress to close out.

Note that most of these are not _necessary_, but i'd feel better wrapping them up, at least to honor the work that's already been put into them.

- [ ] Open PRs:
  - [x] #988
  - [x] #980
  - [x] #687
  - [x] #970
  - [x] #963 - reviewed, waiting on author response
  - [ ] #945 - draft?
  - [ ] #918 - draft, incomplete?
- [x] Small changes to streamline project setup and approachability
  - [x] Better explain how vue is integrated into the app and rename `EntryPoints` (#995)
  - [x] Add `foreman` or other tool to automatically startup rails, webpack and mailcatcher (#997)
  - [x] Document integration between `blueprinter` and `pundit`.
  - [x] Document `Context` object pattern.
- [x] Maintenance backlog
  - [x] Upgrade webpack and webpacker -- upgraded as far as possible in #998, pending release of v6.0 
  - [x] Resolve [dependabot alerts](https://github.com/rubyforgood/mutual-aid/security/dependabot) -- most addressed in #998, remaining require webpacker v6.
- [x] Cut another release and deploy to demo, test
- [x] Issues
  - [x] Close any obsolete issues
  - [x] Clearly mark any remaining bugs
  - [x] Collapse all remaining non-bug issues into a single #1001
  - [x] Cleanup Roadmap project
- [x] Documentation
  - [x] Remove any outdated mentions (eg of RfG, hacktoberfest, etc)
  - [x] Add some language to indicate current status of the project
- [x] Clean up inactive/stale branches

**Comment by solebared** [comment]
Pretty much done, so closing this out. Only outstanding things are a few open PRs and some inactive branches.

@h-m-m, #945 looks like a draft, so i'll let you handle that one. Also #1005 came out of a spike you and i discussed at some point; will leave up to you as well.

@maebeale, @svileshina, @Connieh1, i'm not sure what to do with #918 . I don't have enough context to know if the whole, or parts, of the outstanding code there is useful.

I merged/closed as many inactive branches as i could. The remainder either seem to have useful commits and/or more going on than i felt comfortable deleting w/o checking with their resp. authors.
